plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.kotlin.serialization)
}

android {
    namespace = "com.cyopstd.game"
    compileSdk = 35

    defaultConfig {
        applicationId = "com.cyopstd.game"
        minSdk = 24
        targetSdk = 35
        versionCode = 17
        versionName = "1.13.0"

        // Stamped into the APK so the build identifier on screen is the real
        // one, not a string someone remembered to update. Reported by
        // BuildStamp and shown on every screen.
        buildConfigField("String", "BUILD_STAMP", "\"${'$'}{System.currentTimeMillis() / 1000}\"")

        // --- Google Play configuration ---------------------------------------
        //
        // Supplied per build rather than hard-coded, and EMPTY BY DEFAULT on
        // purpose: an unset id selects the no-op gateway, so a checkout with no
        // Play Console behind it builds and runs exactly as before. Set them in
        // a local gradle.properties (which is not committed) or in CI:
        //
        //     cyops.admob.appId=ca-app-pub-XXXXXXXX~YYYYYYYY
        //     cyops.admob.interstitialId=ca-app-pub-XXXXXXXX/ZZZZZZZZ
        //
        // The AdMob *application* id must also reach the manifest, which is why
        // it is a manifest placeholder as well as a BuildConfig field.
        val admobAppId = (project.findProperty("cyops.admob.appId") as String?).orEmpty()
        val admobInterstitial =
            (project.findProperty("cyops.admob.interstitialId") as String?).orEmpty()

        buildConfigField("String", "ADMOB_APP_ID", "\"${'$'}admobAppId\"")
        buildConfigField("String", "ADMOB_INTERSTITIAL_ID", "\"${'$'}admobInterstitial\"")

        // The SDK refuses to initialise without a syntactically valid id, so an
        // unconfigured build gets Google's documented sample application id.
        // Nothing is ever requested from it, because AdGateways.create() returns
        // the no-op gateway when the real ids are absent.
        manifestPlaceholders["admobAppId"] = admobAppId.ifEmpty {
            "ca-app-pub-3940256099942544~3347511713"
        }
        // Keep the APK small: the game ships no localized resources yet.
        resourceConfigurations += listOf("en")
    }

    signingConfigs {
        create("releaseLocal") {
            // Self-signed key generated by tools/generate-keystore.sh so that a
            // signed, installable release APK can be produced offline.
            val ksFile = rootProject.file("keystore/cyopstd.jks")
            if (ksFile.exists()) {
                storeFile = ksFile
                storePassword = "cyopstd"
                keyAlias = "cyopstd"
                keyPassword = "cyopstd"
            }
        }
    }

    buildTypes {
        debug {
            isMinifyEnabled = false
            applicationIdSuffix = ".debug"
            versionNameSuffix = "-debug"
        }
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
            val ksFile = rootProject.file("keystore/cyopstd.jks")
            if (ksFile.exists()) {
                signingConfig = signingConfigs.getByName("releaseLocal")
            }
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    buildFeatures {
        compose = true
        buildConfig = true
    }

    testOptions {
        unitTests {
            // Robolectric drives the real Compose UI on the JVM, which needs the
            // merged Android resources on the unit-test classpath.
            isIncludeAndroidResources = true
            isReturnDefaultValues = true

            all {
                it.systemProperty("robolectric.logging.enabled", "false")
                // Robolectric downloads its android-all runtime itself rather
                // than through Gradle's repositories, so it needs the mirror
                // pointed out to it separately (see settings.gradle.kts).
                it.systemProperty(
                    "robolectric.dependency.repo.url",
                    "https://maven-central.storage-download.googleapis.com/maven2"
                )
                it.systemProperty("robolectric.dependency.repo.id", "central-mirror")
                // Each fork re-resolves the runtime; one fork keeps that to a
                // single download and avoids racing on the shared cache.
                it.maxParallelForks = 1
            }
        }
    }

    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
            excludes += "DebugProbesKt.bin"
            excludes += "kotlin-tooling-metadata.json"
        }
    }

    applicationVariants.all {
        outputs.all {
            val output = this as com.android.build.gradle.internal.api.BaseVariantOutputImpl
            output.outputFileName = if (buildType.name == "release") {
                "CyOpsTD-v${versionName}.apk"
            } else {
                "app-${buildType.name}.apk"
            }
        }
    }
}

dependencies {
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.lifecycle.runtime.compose)
    implementation(libs.androidx.lifecycle.viewmodel.compose)
    implementation(libs.androidx.activity.compose)
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.compose.ui)
    implementation(libs.androidx.compose.ui.graphics)
    implementation(libs.androidx.compose.ui.tooling.preview)
    implementation(libs.androidx.compose.material3)
    implementation(libs.androidx.navigation.compose)
    implementation(libs.androidx.datastore.preferences)
    implementation(libs.kotlinx.serialization.json)

    // Google Play. Both are optional at runtime: the app selects a no-op
    // gateway when the ids below are unset, so a build with no Play Console
    // behind it still runs and still plays.
    implementation(libs.billing.ktx)
    implementation(libs.play.services.ads)
    debugImplementation(libs.androidx.compose.ui.tooling)

    testImplementation(libs.junit)
    testImplementation(libs.robolectric)
    testImplementation(libs.kotlinx.coroutines.test)
    testImplementation(platform(libs.androidx.compose.bom))
    testImplementation(libs.androidx.compose.ui.test.junit4)
    debugImplementation(libs.androidx.compose.ui.test.manifest)
}
