plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.kotlin.serialization)
}

android {
    namespace = "com.cyopstd.game"
    compileSdk = 35

    defaultConfig {
        applicationId = "com.cyopstd.game"
        minSdk = 24
        targetSdk = 35
        versionCode = 9
        versionName = "1.6.0"
        // Keep the APK small: the game ships no localized resources yet.
        resourceConfigurations += listOf("en")
    }

    signingConfigs {
        create("releaseLocal") {
            // Self-signed key generated by tools/generate-keystore.sh so that a
            // signed, installable release APK can be produced offline.
            val ksFile = rootProject.file("keystore/cyopstd.jks")
            if (ksFile.exists()) {
                storeFile = ksFile
                storePassword = "cyopstd"
                keyAlias = "cyopstd"
                keyPassword = "cyopstd"
            }
        }
    }

    buildTypes {
        debug {
            isMinifyEnabled = false
            applicationIdSuffix = ".debug"
            versionNameSuffix = "-debug"
        }
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
            val ksFile = rootProject.file("keystore/cyopstd.jks")
            if (ksFile.exists()) {
                signingConfig = signingConfigs.getByName("releaseLocal")
            }
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    buildFeatures {
        compose = true
        buildConfig = true
    }

    testOptions {
        unitTests {
            // Robolectric drives the real Compose UI on the JVM, which needs the
            // merged Android resources on the unit-test classpath.
            isIncludeAndroidResources = true
            isReturnDefaultValues = true

            all {
                it.systemProperty("robolectric.logging.enabled", "false")
                // Robolectric downloads its android-all runtime itself rather
                // than through Gradle's repositories, so it needs the mirror
                // pointed out to it separately (see settings.gradle.kts).
                it.systemProperty(
                    "robolectric.dependency.repo.url",
                    "https://maven-central.storage-download.googleapis.com/maven2"
                )
                it.systemProperty("robolectric.dependency.repo.id", "central-mirror")
                // Each fork re-resolves the runtime; one fork keeps that to a
                // single download and avoids racing on the shared cache.
                it.maxParallelForks = 1
            }
        }
    }

    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
            excludes += "DebugProbesKt.bin"
            excludes += "kotlin-tooling-metadata.json"
        }
    }

    applicationVariants.all {
        outputs.all {
            val output = this as com.android.build.gradle.internal.api.BaseVariantOutputImpl
            output.outputFileName = if (buildType.name == "release") {
                "CyOpsTD-v${versionName}.apk"
            } else {
                "app-${buildType.name}.apk"
            }
        }
    }
}

dependencies {
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.lifecycle.runtime.compose)
    implementation(libs.androidx.lifecycle.viewmodel.compose)
    implementation(libs.androidx.activity.compose)
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.compose.ui)
    implementation(libs.androidx.compose.ui.graphics)
    implementation(libs.androidx.compose.ui.tooling.preview)
    implementation(libs.androidx.compose.material3)
    implementation(libs.androidx.navigation.compose)
    implementation(libs.androidx.datastore.preferences)
    implementation(libs.kotlinx.serialization.json)
    debugImplementation(libs.androidx.compose.ui.tooling)

    testImplementation(libs.junit)
    testImplementation(libs.robolectric)
    testImplementation(libs.kotlinx.coroutines.test)
    testImplementation(platform(libs.androidx.compose.bom))
    testImplementation(libs.androidx.compose.ui.test.junit4)
    debugImplementation(libs.androidx.compose.ui.test.manifest)
}
