#!/usr/bin/env python3
"""
Regenerates res/drawable/hamieton_banner.xml from DEVELOPER_BANNER.

The wordmark is a drawable rather than text because the text version could not
be made to render correctly on real hardware -- row spacing depends on the
metrics of a monospace font chosen at runtime, and those differ by device.
This keeps the ASCII look (every cell is still a drawn '#') while removing the
font from the equation entirely.

    python3 tools/build_banner.py
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(
    ROOT, "app/src/main/java/com/cyopstd/game/ui/splash/DeveloperSplashScreen.kt"
)
TARGET = os.path.join(ROOT, "app/src/main/res/drawable/hamieton_banner.xml")
CELL = 10


def banner_lines():
    src = open(SOURCE).read()
    marker = 'val DEVELOPER_BANNER: String = """'
    block = src[src.index(marker) + len(marker):]
    block = block[: block.index('"""')]
    lines = [l for l in block.split("\n") if l.strip()]
    indent = min(len(l) - len(l.lstrip()) for l in lines)
    lines = [l[indent:] for l in lines]
    width = max(len(l) for l in lines)
    return [l.ljust(width) for l in lines]


def rect(x, y, w, h):
    return f"M{x:.1f},{y:.1f}h{w:.1f}v{h:.1f}h{-w:.1f}z"


def skew_bar(x, y, w, h, lean):
    """A parallelogram: the verticals of a '#' lean right, like the glyph."""
    return f"M{x + lean:.1f},{y:.1f}h{w:.1f}l{-lean:.1f},{h:.1f}h{-w:.1f}z"


def main():
    lines = banner_lines()
    rows, cols = len(lines), len(lines[0])
    subpaths = []
    for r, line in enumerate(lines):
        for c, ch in enumerate(line):
            if ch != "#":
                continue
            ox, oy = c * CELL, r * CELL
            subpaths.append(rect(ox + 0.8, oy + 3.4, 8.4, 1.5))
            subpaths.append(rect(ox + 0.8, oy + 5.9, 8.4, 1.5))
            subpaths.append(skew_bar(ox + 2.9, oy + 1.2, 1.5, 7.6, 1.1))
            subpaths.append(skew_bar(ox + 5.6, oy + 1.2, 1.5, 7.6, 1.1))

    open(TARGET, "w").write(
        '<?xml version="1.0" encoding="utf-8"?>\n'
        "<!--\n  Generated by tools/build_banner.py. Do not edit by hand.\n-->\n"
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        f'    android:width="{cols * 4}dp"\n'
        f'    android:height="{rows * 4}dp"\n'
        f'    android:viewportWidth="{cols * CELL}"\n'
        f'    android:viewportHeight="{rows * CELL}">\n'
        '    <path\n        android:fillColor="#FFFFFFFF"\n'
        f'        android:pathData="{"".join(subpaths)}" />\n'
        "</vector>\n"
    )
    print(f"{TARGET}: {cols}x{rows} cells, {len(subpaths)} subpaths")
    return 0


if __name__ == "__main__":
    sys.exit(main())
