#!/usr/bin/env bash
#
# Generate a LOCAL, THROWAWAY signing key so that a signed, installable release
# APK can be produced on this machine.
#
# This is NOT your Play upload key. Read PLAY_STORE_RELEASE.md for that; the
# upload key should be created deliberately, backed up in two places, and never
# generated by a script that lives in the repository.
#
# What this does:
#   - creates keystore/cyopstd-local.jks          (git-ignored)
#   - writes the four signing values into secrets.properties (git-ignored)
#   - uses a RANDOM password, not one written down in this file
#
# The password being random is the point. An earlier version of this script
# used a fixed password that was also a string literal in app/build.gradle.kts,
# which put a password in source control however throwaway the key was.
#
# NOTE: do not regenerate a key that has already signed a build someone
# installed. Android refuses to upgrade an app whose signing key changed, so a
# new key turns every future build into an uninstall-first situation.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
KEYSTORE_DIR="$ROOT/keystore"
KEYSTORE="$KEYSTORE_DIR/cyopstd-local.jks"
SECRETS="$ROOT/secrets.properties"
ALIAS="cyopstd-local"

if [ -f "$KEYSTORE" ]; then
    echo "Keystore already exists: $KEYSTORE"
    echo "Delete it yourself if you really want to regenerate (see the note above)."
    exit 0
fi

# Refuse to run if the files somehow are not ignored -- better to stop than to
# write a private key into a tracked path.
for path in "keystore/" "secrets.properties"; do
    if ! git -C "$ROOT" check-ignore -q "$path"; then
        echo "REFUSING: '$path' is not git-ignored. Fix .gitignore first."
        exit 1
    fi
done

mkdir -p "$KEYSTORE_DIR"
PASSWORD="$(LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c 32)"

keytool -genkeypair -v \
    -keystore "$KEYSTORE" \
    -storepass "$PASSWORD" \
    -keypass "$PASSWORD" \
    -alias "$ALIAS" \
    -keyalg RSA -keysize 4096 -validity 10000 \
    -dname "CN=CyOps TD local build, OU=Local, O=Local, L=Local, S=Local, C=ZZ"

touch "$SECRETS"
# Replace any existing signing block rather than appending a second one.
if grep -q "^cyops.keystore.path=" "$SECRETS" 2>/dev/null; then
    echo
    echo "secrets.properties already has signing values; leaving them alone."
    echo "The new keystore is at: $KEYSTORE"
    echo "Its password is: $PASSWORD"
    echo "(Write that down now -- it is not stored anywhere else.)"
    exit 0
fi

cat >> "$SECRETS" <<EOF

# Local throwaway signing key, generated by tools/generate-keystore.sh.
# NOT a Play upload key -- see PLAY_STORE_RELEASE.md.
cyops.keystore.path=$KEYSTORE
cyops.keystore.password=$PASSWORD
cyops.key.alias=$ALIAS
cyops.key.password=$PASSWORD
EOF

echo
echo "Done."
echo "  keystore : $KEYSTORE"
echo "  secrets  : $SECRETS  (git-ignored)"
echo
echo "./gradlew assembleRelease will now produce a signed local APK."
echo "This key is for local installs only. It is not your Play upload key."
